- name: Create the builder user
  become: true
  ansible.builtin.user:
    name: "{{ aur_user_name }}"
    create_home: true
    group: wheel

- name: Allow the builder user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "{{ aur_user_name }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    mode: 0644
    validate: 'visudo -cf %s'
