- name: Install programming software
  become: true
  become_user: "{{ aur_user_name }}"
  kewlfft.aur.aur:
    name: "{{ programming_software }}"
    use: "{{ aur_package_manager }}"
    state: present
    extra_args:
      - noconfirm
  changed_when: false
